services:
  mysql:
    image: mysql:9.1.0-oraclelinux9
    restart: always
    container_name: devstream-mysql
    env_file:
      - .env
    ports:
      - "3306:3306" # make sure you don't have another container running on 3306
    volumes:
      - mysql_volume:/var/lib/mysql
      
  backend:
    container_name: devstream-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_REPO_USERNAME
        - GITHUB_REPO_PASSWORD
    env_file:
      - .env
    ports:
      - "8080:6969"
    depends_on:
      - mysql

volumes:
  mysql_volume:
