spring:
  application:
    name: omnistream
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      host: localhost
      port: 27017
      database: devstream
server:
  port: 6969
