spring:
  application:
    name: omnistream
  jpa:
    hibernate:
      show-sql: false
      ddl-auto: update
  datasource:
    # https://stackoverflow.com/questions/47580247/optional-environment-variables-in-spring-app
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

server:
  port: 6969
