spring:
  application:
    name: omnistream
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
  datasource: 
    # https://stackoverflow.com/questions/47580247/optional-environment-variables-in-spring-app
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

auth:
  jwt:
    issuer: devstream.in
    audience: omnistream-application
    ttl-in-seconds: ${JWT_TTL_IN_SECONDS}
    secret-key: ${JWT_AUTH_SECRET_KEY}

server:
  port: 6969
